language: node_js
node_js:
  - node
  - lts/*
script:
  - npm test
  - npm run codecov
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: main
